services:
  db:
    image: 'postgres:17-alpine'
    environment:
      POSTGRES_USER: ${DB_USR?:pollsapp}
      POSTGRES_PASSWORD: ${DB_PASSWD?:password}
      POSTGRES_DB: ${DB_NAME?:pollsdb}
      PGDATA: /pgdata
    volumes:
      - type: bind
        source: ./db
        target: /pgdata
    expose:
      - 5432
    ports:
      - '5432:5432'
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d polls -U $$POSTGRES_USER
      start_period: 10s
      interval: 5s
      retries: 10
  app:
    build: .
    env_file: .env
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      TIME_ZONE: ${TIME_ZONE}
      CONTAINED: True
      LOAD_DATA: ${LOAD_DATA}
    ports:
      - '8000:8000'
    depends_on:
      - db
