# Generated by Django 5.1 on 2024-08-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_input_response_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='key',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
