# Generated by Django 5.1 on 2024-08-21 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_poll_creator_poll_limit_alter_session_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='limit',
            new_name='allow',
        ),
    ]
