# Generated by Django 5.1 on 2024-08-20 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_poll_pub_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Input',
            new_name='Response',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
