name: tests
run-name: ${{ github.actor }} is testing the project.
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python ./manage.py test
